when:
  branch: master
  event: [push, pull_request]

variables:
  - &file Dockerfile
  - &repo harbor.fullstackjam.dev/app/portfolio
  - &commit_hash ${DRONE_COMMIT_SHA:0:7}

steps:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: linux/amd64
      repo: *repo
      registry: harbor.fullstackjam.dev
      tags:
        - latest
        - ${COMMIT_HASH}
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
