when:
  branch: master
  event: [push, pull_request]

variables:
  - &file Dockerfile
  - &repo registry.fullstackjam.dev/app/portfolio

steps:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    environment:
      COMMIT_HASH: ${DRONE_COMMIT_SHA:0:7}
    settings:
      dockerfile: *file
      platforms: linux/amd64
      repo: *repo
      registry: registry.fullstackjam.dev
      tags:
        - latest
        - ${COMMIT_HASH}
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
