when:
  branch: master
  event: [push, pull_request]

variables:
  - &file Dockerfile
  - &repo registry.fullstackjam.dev/portfolio
  - &commit_hash ${DRONE_COMMIT_SHA:0:7}

steps:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: linux/amd64
      repo: *repo
      registry: registry.fullstackjam.dev
      tags:
        - latest
        - ${COMMIT_HASH}
