replicaCount: 1

image:
  repository: registry.fullstackjam.dev/portfolio
  pullPolicy: Always
  tag: latest

ingress:
  enabled: true
  hosts:
    - host: portfolio.fullstackjam.dev
  tlsSecret: portfolio-tls-certificate
