replicaCount: 3

image:
  repository: registry.fullstackjam.dev/app/portfolio
  pullPolicy: Always
  tag: latest

ingress:
  enabled: true
  host: portfolio.fullstackjam.dev
  tlsSecret: portfolio-tls-certificate
