replicaCount: 1

image:
  repository: fullstackjam/portfolio
  pullPolicy: Always
  tag: latest

ingress:
  enabled: true
  hosts:
    - host: portfolio.fullstackjam.com
  tlsSecret: portfolio-tls-certificate
