apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portfolio
spec:
  entryPoints:
    - websecure
  routes:
  {{- range .Values.ingressRoute.domains }}
    - match: Host(`{{ . }}`)
      kind: Rule
      services:
        - name: portfolio
          port: 80
  {{- end }}
  tls:
    certResolver: myresolver
